#!/bin/bash


declare -i x=1



mkdir datas

FILES=../data/Scenes/*.json
for f in $FILES
do
  echo "Processing $f file..."
  ./SPHSimulator --no-gui --stopAt 3 $f
  
  cd datas
  
  mkdir $x
  
  cd ..
  
  path="./datas/$x"
  
  mv simdata.csv $path
  mv simulation_sample.bin $path
  
  x=x+1
  
done

echo "Done!"
